services:
  mongo:
    image: mongo:4.2
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    command: ["--bind_ip", "0.0.0.0"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fashion-cloud-app
    container_name: fashion-cloud-app
    restart: on-failure
    depends_on:
      - mongo
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - 8080=8080
      - DATA_STORE_MONGODB_HOST=mongo
      - DATA_STORE_MONGODB_PORT=27017
      - CACHE_TTL_IN_SECONDS=300
      - CACHE_LIMIT=1000


